#pragma once

static const char INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>BLE Scanner \xe2\x80\x94 PowerStream Bridge</title>\n"
"<style>\n"
"body{font-family:monospace;background:#111;color:#ddd;margin:2rem}\n"
"h1{color:#4af;margin-bottom:.3rem}\n"
"#status{font-size:.8rem;color:#888;margin-bottom:1rem}\n"
"table{border-collapse:collapse;width:100%}\n"
"th,td{border:1px solid #333;padding:.4rem .8rem;text-align:left}\n"
"th{background:#222;color:#adf;cursor:pointer;user-select:none}\n"
"th:hover{background:#2a2a2a}\n"
"tr.ecoflow{background:#1a2a1a}\n"
"tr.ecoflow td:first-child::after{content:\" \xe2\x9a\xa1\";color:#6f6}\n"
".rssi-strong{color:#6f6}\n"
".rssi-medium{color:#fa0}\n"
".rssi-weak{color:#f44}\n"
"#count{font-size:.85rem;color:#888;margin-top:.5rem}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<h1>BLE Scanner</h1>\n"
"<div id=\"status\">Connecting\xe2\x80\xa6</div>\n"
"<table>\n"
"<thead><tr>\n"
"<th onclick=\"sortBy('name')\">Name</th>\n"
"<th onclick=\"sortBy('mac')\">MAC</th>\n"
"<th onclick=\"sortBy('rssi')\">RSSI</th>\n"
"<th onclick=\"sortBy('age')\">Last seen</th>\n"
"</tr></thead>\n"
"<tbody id=\"tbody\"></tbody>\n"
"</table>\n"
"<div id=\"count\"></div>\n"
"<script>\n"
"let devices=[],sortKey='rssi',sortAsc=true;\n"
"function rssiClass(r){return r>=-60?'rssi-strong':r>=-80?'rssi-medium':'rssi-weak';}\n"
"function render(){\n"
"const s=[...devices].sort((a,b)=>{\n"
"let av=a[sortKey],bv=b[sortKey];\n"
"if(typeof av==='string'){av=av.toLowerCase();bv=bv.toLowerCase();}\n"
"return sortAsc?(av>bv?1:-1):(av<bv?1:-1);});\n"
"document.getElementById('tbody').innerHTML=s.map(d=>{\n"
"const ef=d.name.startsWith('HW51')||d.name.startsWith('EF-HW');\n"
"const age=d.age<5?'now':d.age+'s ago';\n"
"return `<tr class=\"${ef?'ecoflow':''}\">`\n"
"+`<td>${esc(d.name||'\\u2014')}</td>`\n"
"+`<td>${esc(d.mac)}</td>`\n"
"+`<td class=\"${rssiClass(d.rssi)}\">${d.rssi} dBm</td>`\n"
"+`<td>${age}</td></tr>`;}).join('');\n"
"document.getElementById('count').textContent=s.length+' device(s)';}\n"
"function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}\n"
"function sortBy(k){if(sortKey===k)sortAsc=!sortAsc;else{sortKey=k;sortAsc=true;}render();}\n"
"async function poll(){\n"
"try{\n"
"const r=await fetch('/api/devices');\n"
"devices=await r.json();\n"
"document.getElementById('status').textContent='Updated '+new Date().toLocaleTimeString();\n"
"render();\n"
"}catch(e){document.getElementById('status').textContent='Error: '+e.message;}}\n"
"poll();setInterval(poll,2000);\n"
"</script>\n"
"</body>\n"
"</html>\n";
