#pragma once

static const char INDEX_HTML[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
"<title>PowerStream Bridge</title>\n"
"<style>\n"
"  body { font-family: monospace; background: #111; color: #ddd; margin: 2rem; }\n"
"  h1   { color: #4af; margin-bottom: 0.3rem; }\n"
"  h2   { color: #4af; font-size: 1rem; margin: 1.5rem 0 0.5rem; }\n"
"  #status { font-size: 0.8rem; color: #888; margin-bottom: 1rem; }\n"
"  table  { border-collapse: collapse; width: 100%; }\n"
"  th, td { border: 1px solid #333; padding: 0.4rem 0.8rem; text-align: left; }\n"
"  th     { background: #222; color: #adf; cursor: pointer; user-select: none; }\n"
"  th:hover { background: #2a2a2a; }\n"
"  tr.ecoflow { background: #1a2a1a; }\n"
"  tr.ecoflow td:first-child::after { content: \" ⚡\"; color: #6f6; }\n"
"  .rssi-strong { color: #6f6; }\n"
"  .rssi-medium { color: #fa0; }\n"
"  .rssi-weak   { color: #f44; }\n"
"  #count { font-size: 0.85rem; color: #888; margin-top: 0.5rem; }\n"
"  #ps { border: 1px solid #2a4; border-radius: 6px; padding: 1rem; background: #141a14; }\n"
"  .badge { display: inline-block; padding: 0.1rem 0.6rem; border-radius: 4px;\n"
"           background: #333; color: #adf; font-weight: bold; }\n"
"  .badge.streaming { background: #1a4a1a; color: #6f6; }\n"
"  .badge.scanning, .badge.disconnected { background: #4a2a1a; color: #fa0; }\n"
"  .psmeta { font-size: 0.8rem; color: #888; margin: 0.4rem 0 0.8rem; }\n"
"  .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));\n"
"          gap: 0.6rem; }\n"
"  .card { border: 1px solid #2a3a2a; border-radius: 5px; padding: 0.6rem; }\n"
"  .card h3 { margin: 0 0 0.4rem; font-size: 0.8rem; color: #8cf; }\n"
"  .card .row { display: flex; justify-content: space-between; font-size: 0.85rem; }\n"
"  .card .row span:last-child { color: #fff; }\n"
"  .dim { opacity: 0.4; }\n"
"  .tabs { margin: 0.5rem 0 1rem; }\n"
"  .tabs button { background: #222; color: #adf; border: 1px solid #333;\n"
"                 padding: 0.4rem 1rem; cursor: pointer; font-family: monospace; }\n"
"  .tabs button.active { background: #1a2a3a; color: #fff; }\n"
"  form label { display: block; margin: 0.8rem 0 0.2rem; color: #8cf; font-size: 0.85rem; }\n"
"  form input { width: 100%; max-width: 360px; padding: 0.4rem; background: #181818;\n"
"               color: #ddd; border: 1px solid #333; font-family: monospace; box-sizing: border-box; }\n"
"  form button { margin-top: 1.2rem; padding: 0.5rem 1.2rem; background: #1a4a1a;\n"
"                color: #6f6; border: 1px solid #2a5a2a; cursor: pointer; font-family: monospace; }\n"
"  .hint { font-size: 0.75rem; color: #777; margin-top: 0.2rem; }\n"
"  .hint a { color: #4af; }\n"
"  #setmsg { margin-top: 1rem; color: #fa0; }\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<h1>PowerStream Bridge</h1>\n"
"<div class=\"tabs\">\n"
"  <button id=\"tb-dash\" class=\"active\" onclick=\"showTab('dash')\">Dashboard</button>\n"
"  <button id=\"tb-stat\" onclick=\"showTab('stat')\">Status</button>\n"
"  <button id=\"tb-log\" onclick=\"showTab('log')\">Log</button>\n"
"  <button id=\"tb-set\" onclick=\"showTab('set')\">Settings</button>\n"
"</div>\n"
"\n"
"<div id=\"tab-dash\">\n"
"<div id=\"status\">Connecting…</div>\n"
"\n"
"<div id=\"ps\">\n"
"  <div><span id=\"psstate\" class=\"badge\">—</span></div>\n"
"  <div class=\"psmeta\" id=\"psmeta\"></div>\n"
"  <div class=\"grid\" id=\"psgrid\"></div>\n"
"</div>\n"
"\n"
"<h2>BLE Scan</h2>\n"
"<table>\n"
"  <thead>\n"
"    <tr>\n"
"      <th onclick=\"sortBy('name')\">Name</th>\n"
"      <th onclick=\"sortBy('mac')\">MAC</th>\n"
"      <th onclick=\"sortBy('rssi')\">RSSI</th>\n"
"      <th onclick=\"sortBy('age')\">Last seen</th>\n"
"    </tr>\n"
"  </thead>\n"
"  <tbody id=\"tbody\"></tbody>\n"
"</table>\n"
"<div id=\"count\"></div>\n"
"</div><!-- /tab-dash -->\n"
"\n"
"<div id=\"tab-stat\" hidden>\n"
"  <h2>Bridge status</h2>\n"
"  <table id=\"stattbl\"><tbody></tbody></table>\n"
"</div><!-- /tab-stat -->\n"
"\n"
"<div id=\"tab-log\" hidden>\n"
"  <h2>Log <label style=\"font-size:0.75rem;color:#888\">\n"
"    <input type=\"checkbox\" id=\"logfollow\" checked> follow</label></h2>\n"
"  <pre id=\"logpre\" style=\"background:#181818;border:1px solid #333;padding:0.8rem;\n"
"       max-height:70vh;overflow:auto;white-space:pre-wrap;font-size:0.75rem\"></pre>\n"
"</div><!-- /tab-log -->\n"
"\n"
"<div id=\"tab-set\" hidden>\n"
"  <form id=\"setform\" onsubmit=\"return saveSettings(event)\">\n"
"    <label>WiFi network (STA SSID)</label>\n"
"    <input id=\"f-ssid\" name=\"wifi_ssid\" autocomplete=\"off\" placeholder=\"leave blank for AP-only\">\n"
"    <label>WiFi password</label>\n"
"    <input id=\"f-pass\" name=\"wifi_pass\" type=\"password\" autocomplete=\"off\" placeholder=\"unchanged\">\n"
"    <div class=\"hint\">Leave blank to keep the current password.</div>\n"
"    <label>EcoFlow account user_id</label>\n"
"    <input id=\"f-uid\" name=\"user_id\" autocomplete=\"off\" placeholder=\"optional — for BLE auth\">\n"
"    <div class=\"hint\">PowerStream serials are auto-detected; only the account user_id may be needed.\n"
"      Find yours at <a href=\"https://gnox.github.io/user_id\" target=\"_blank\" rel=\"noopener\">gnox.github.io/user_id</a>\n"
"      (enter your EcoFlow login once — it's used only to query the API and is not stored).</div>\n"
"    <button type=\"submit\">Save &amp; reboot</button>\n"
"    <div id=\"setmsg\"></div>\n"
"  </form>\n"
"\n"
"  <h2>Firmware update</h2>\n"
"  <input type=\"file\" id=\"fwfile\" accept=\".bin\">\n"
"  <button onclick=\"uploadFw()\">Flash &amp; reboot</button>\n"
"  <div class=\"hint\">Upload firmware.bin from .pio/build/esp32-c6-devkitc-1/ —\n"
"    or: curl --data-binary @firmware.bin http://&lt;ip&gt;/api/ota</div>\n"
"  <div id=\"fwmsg\"></div>\n"
"</div><!-- /tab-set -->\n"
"\n"
"<script>\n"
"let devices = [];\n"
"let sortKey = 'rssi';\n"
"let sortAsc  = true;\n"
"\n"
"let curTab = 'dash';\n"
"function showTab(t) {\n"
"  curTab = t;\n"
"  for (const n of ['dash', 'stat', 'log', 'set']) {\n"
"    document.getElementById('tab-' + n).hidden = t !== n;\n"
"    document.getElementById('tb-' + n).classList.toggle('active', t === n);\n"
"  }\n"
"  if (t === 'set') loadSettings();\n"
"  if (t === 'stat') pollStatus();\n"
"  if (t === 'log') pollLog();\n"
"}\n"
"\n"
"async function pollStatus() {\n"
"  try {\n"
"    const s = await fetch('/api/status').then(r => r.json());\n"
"    const up = s.uptime_s, h = Math.floor(up/3600), m = Math.floor(up%3600/60);\n"
"    const rows = [\n"
"      ['Hostname', s.hostname],\n"
"      ['Uptime', h + 'h ' + m + 'm ' + (up%60) + 's'],\n"
"      ['Free heap', Math.round(s.heap_free/1024) + ' KB'],\n"
"      ['WiFi client (STA)', s.sta.enabled ?\n"
"        (s.sta.connected ? 'connected' : 'DISCONNECTED (retry #' + s.sta.retries + ')')\n"
"        : 'not configured'],\n"
"      ['STA network', s.sta.ssid || '—'],\n"
"      ['STA IP', s.sta.ip],\n"
"      ['STA signal', s.sta.connected ? s.sta.rssi + ' dBm' : '—'],\n"
"      ['Access point', s.ap.ssid + ' @ ' + s.ap.ip],\n"
"      ['AP clients', s.ap.clients],\n"
"    ];\n"
"    document.querySelector('#stattbl tbody').innerHTML =\n"
"      rows.map(r => `<tr><td>${r[0]}</td><td>${esc(String(r[1]))}</td></tr>`).join('');\n"
"  } catch (e) {}\n"
"}\n"
"\n"
"async function pollLog() {\n"
"  try {\n"
"    const txt = await fetch('/api/log').then(r => r.text());\n"
"    const pre = document.getElementById('logpre');\n"
"    pre.textContent = txt;\n"
"    if (document.getElementById('logfollow').checked)\n"
"      pre.scrollTop = pre.scrollHeight;\n"
"  } catch (e) {}\n"
"}\n"
"\n"
"async function loadSettings() {\n"
"  try {\n"
"    const s = await fetch('/api/settings').then(r => r.json());\n"
"    document.getElementById('f-ssid').value = s.wifi_ssid || '';\n"
"    document.getElementById('f-uid').value = s.user_id || '';\n"
"    document.getElementById('f-pass').placeholder = s.wifi_pass_set ? 'unchanged' : '(none set)';\n"
"  } catch (e) {}\n"
"}\n"
"\n"
"async function saveSettings(ev) {\n"
"  ev.preventDefault();\n"
"  const body = new URLSearchParams(new FormData(document.getElementById('setform'))).toString();\n"
"  document.getElementById('setmsg').textContent = 'Saving…';\n"
"  try {\n"
"    await fetch('/api/settings', { method: 'POST',\n"
"      headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body });\n"
"  } catch (e) {}\n"
"  document.getElementById('setmsg').textContent =\n"
"    'Saved. Device is rebooting — reconnect in ~10 s (new IP if WiFi changed).';\n"
"  return false;\n"
"}\n"
"\n"
"async function uploadFw() {\n"
"  const f = document.getElementById('fwfile').files[0];\n"
"  const msg = document.getElementById('fwmsg');\n"
"  if (!f) { msg.textContent = 'Pick a firmware.bin first.'; return; }\n"
"  msg.textContent = 'Uploading ' + Math.round(f.size/1024) + ' KB…';\n"
"  try {\n"
"    const r = await fetch('/api/ota', { method: 'POST', body: f });\n"
"    const j = await r.json();\n"
"    msg.textContent = j.ok ? 'Flashed OK — rebooting, reconnect in ~10 s.'\n"
"                           : 'Failed: ' + (j.err || r.status);\n"
"  } catch (e) { msg.textContent = 'Upload failed: ' + e.message; }\n"
"}\n"
"\n"
"function rssiClass(r) {\n"
"  return r >= -60 ? 'rssi-strong' : r >= -80 ? 'rssi-medium' : 'rssi-weak';\n"
"}\n"
"\n"
"function esc(s) {\n"
"  return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');\n"
"}\n"
"\n"
"function render() {\n"
"  const sorted = [...devices].sort((a, b) => {\n"
"    let av = a[sortKey], bv = b[sortKey];\n"
"    if (typeof av === 'string') av = av.toLowerCase(), bv = bv.toLowerCase();\n"
"    return sortAsc ? (av > bv ? 1 : -1) : (av < bv ? 1 : -1);\n"
"  });\n"
"  const tbody = document.getElementById('tbody');\n"
"  tbody.innerHTML = sorted.map(d => {\n"
"    const ef = d.name.startsWith('HW51') || d.name.startsWith('EF-HW');\n"
"    const age = d.age < 5 ? 'now' : d.age + 's ago';\n"
"    return `<tr class=\"${ef ? 'ecoflow' : ''}\">\n"
"      <td>${esc(d.name || '—')}</td>\n"
"      <td>${esc(d.mac)}</td>\n"
"      <td class=\"${rssiClass(d.rssi)}\">${d.rssi} dBm</td>\n"
"      <td>${age}</td>\n"
"    </tr>`;\n"
"  }).join('');\n"
"  document.getElementById('count').textContent = sorted.length + ' device(s)';\n"
"}\n"
"\n"
"function sortBy(k) {\n"
"  if (sortKey === k) sortAsc = !sortAsc; else { sortKey = k; sortAsc = true; }\n"
"  render();\n"
"}\n"
"\n"
"function row(label, val, unit) {\n"
"  return `<div class=\"row\"><span>${label}</span><span>${val}${unit}</span></div>`;\n"
"}\n"
"function f(raw, div, dec) { return (raw / div).toFixed(dec); }\n"
"\n"
"function renderPS(d) {\n"
"  const st = document.getElementById('psstate');\n"
"  st.textContent = d.state;\n"
"  st.className = 'badge ' + d.state;\n"
"\n"
"  let meta = '';\n"
"  if (d.device) meta += d.device + '  ';\n"
"  if (d.mac) meta += d.mac + '  ';\n"
"  if (d.rssi) meta += d.rssi + ' dBm  ';\n"
"  if (d.valid) meta += '• ' + d.count + ' heartbeats, last ' +\n"
"                       (d.age < 5 ? 'now' : d.age + 's ago');\n"
"  document.getElementById('psmeta').textContent = meta;\n"
"\n"
"  const grid = document.getElementById('psgrid');\n"
"  if (!d.valid) {\n"
"    grid.innerHTML = '<div class=\"card dim\">Waiting for first heartbeat…</div>';\n"
"    return;\n"
"  }\n"
"  const inv = d.inv, pv1 = d.pv1, pv2 = d.pv2, bat = d.bat;\n"
"  grid.innerHTML =\n"
"    `<div class=\"card\"><h3>Inverter (AC out)</h3>\n"
"       ${row('Power', f(inv.w,10,1), ' W')}\n"
"       ${row('Voltage', f(inv.v,10,1), ' V')}\n"
"       ${row('Current', f(inv.a,1000,2), ' A')}\n"
"       ${row('Frequency', f(inv.hz,10,1), ' Hz')}\n"
"       ${row('Temp', f(inv.t,10,1), ' °C')}</div>\n"
"     <div class=\"card\"><h3>PV1</h3>\n"
"       ${row('Power', f(pv1.w,10,1), ' W')}\n"
"       ${row('Voltage', f(pv1.v,10,1), ' V')}\n"
"       ${row('Current', f(pv1.a,10,1), ' A')}\n"
"       ${row('Temp', f(pv1.t,10,1), ' °C')}</div>\n"
"     <div class=\"card\"><h3>PV2</h3>\n"
"       ${row('Power', f(pv2.w,10,1), ' W')}\n"
"       ${row('Voltage', f(pv2.v,10,1), ' V')}\n"
"       ${row('Current', f(pv2.a,10,1), ' A')}\n"
"       ${row('Temp', f(pv2.t,10,1), ' °C')}</div>\n"
"     <div class=\"card\"><h3>Battery</h3>\n"
"       ${row('Power', f(bat.w,10,1), ' W')}\n"
"       ${row('SOC', bat.soc, ' %')}\n"
"       ${row('Temp', f(bat.t,10,1), ' °C')}</div>\n"
"     <div class=\"card\"><h3>Other</h3>\n"
"       ${row('Load set', f(d.load_w,10,1), ' W')}\n"
"       ${row('LLC temp', f(d.llc_t,10,1), ' °C')}\n"
"       ${row('Limit', d.limit_lo + '–' + d.limit_hi, ' %')}</div>`;\n"
"}\n"
"\n"
"async function poll() {\n"
"  if (curTab === 'stat') pollStatus();\n"
"  if (curTab === 'log') pollLog();\n"
"  try {\n"
"    const [dev, ps] = await Promise.all([\n"
"      fetch('/api/devices').then(r => r.json()),\n"
"      fetch('/api/powerstream').then(r => r.json()),\n"
"    ]);\n"
"    devices = dev;\n"
"    renderPS(ps);\n"
"    render();\n"
"    document.getElementById('status').textContent =\n"
"      'Updated ' + new Date().toLocaleTimeString();\n"
"  } catch (e) {\n"
"    document.getElementById('status').textContent = 'Error: ' + e.message;\n"
"  }\n"
"}\n"
"\n"
"poll();\n"
"setInterval(poll, 2000);\n"
"</script>\n"
"</body>\n"
"</html>\n"
;
